### ISSUE TITLE
Update Server to the latest client version

### ISSUE THREAD

**Issue by cbacon93** [evemuproject/evemu_server#137]
I'd like to update the server to the latest client version. Anything i should know before i start?

**Comment by Reve** [comment]
Hi,

There are many issues regarding this task.

1) You need to know the new packet format because they changed it. Any packet structure used now will not work.
2) You will need to build a new packet sniffer in order to grab packets. At the moment the old packet sniffer fails since they updated some stuff and it's harder do hook the executable to inject code.
3) You will need to create a new patcher in order to change the server to which the client is connecting.
4) You will need to get a new database dump and reconstruct the data base structure.

After you are done with the steps above, you have to create all the packets from srcatch (to log in, choose character, etc.). This, as you can see, it's a titanic work and it's not feasible. If you want to contribute with work, I suggest going to the wiki so you can read more about the development process.

Best of luck,
Reve - Former Core Developer

**Comment by cbacon93** [comment]
Hi, I guess I better start looking for the crucible client and try to contribute to this project with the current client version.
