### ISSUE TITLE
Revamp singletons

### ISSUE THREAD

**Issue by eve-moo** [evemuproject/evemu_server#145]
In looking at the singletons class I think it could be done better.  The singleton template can be scraped, the constructors on all singleton classes can be make private.  Then they each get there own get function as follows.
static SingletonClass Get(){
  static SingletonClass instance;
  return instance;
}
We can also get rid of all the #defines for getting the singletons as well.  This link explains some of the reason.
https://isocpp.org/wiki/faq/inline-functions#inline-vs-macros
While the macro may make the code "look" nicer it can mess with code completion and navigation in some IDEs.  As well as the fact that many programmers consider macros bad!
It may also be better to change some of the singleton classes to all static.  That could remove the call to get() and make the code faster.
These changes would also be more consistent with modern programming practices.

**Comment by zhyrohaad** [comment]
I agree that _macro_ and _#define_ are both evil in C++, but this is because of the potential plethora of problems that can come from writing code that isnt thought out very well.  there is much more information about this on the isocpp.org site. 

as a comment on one of your commits, after this issue was opened, i mention it here as it relates to the conversation at hand.
singleton vs. static...yes, im sure there are MANY things in our current codebase that can be done better, the singleton implementation is one of them.
a static class just means that it has static methods, not necessarily a single instance.
the classes defined as singletons in the server are required to have only one instance for the server to operate properly with multiple clients.  entitylist is a prime example of this.  once multiple instances of this class are created, odd things start happening.  i mention this from experience.
